### ISSUE TITLE
Unparsed code omits necessary parens

### ISSUE THREAD

**Issue by dkubb** [mbj/unparser#83]
I had a private method like this:

```ruby
def set_effective(started_at: started_at(), ended_at: ended_at())
  started_at, ended_at = [started_at, ended_at]
    .map(&self.class.method(:coerce_time))
  self.effective =
    if started_at && ended_at && started_at < ended_at
      started_at...ended_at
    end
end
```

And it was being unparsed to:

```ruby
def set_effective(started_at: started_at, ended_at: ended_at)
  started_at, ended_at = [started_at, ended_at]
    .map(&self.class.method(:coerce_time))
  self.effective =
    if started_at && ended_at && started_at < ended_at
      started_at...ended_at
    end
end
```

Note the loss of parenthesis on the method's default option values.

**Comment by mbj** [comment]
I confirm this is a bug in unparser, unparser needs to detect that the lvar is in scope and it has to differentiate the method call from the lvar in the concrete syntax it generates with a meaningul parens pair.

**Comment by catmando** [comment]
I see the same problem with this AST:

```ruby
 s(:class,
  s(:const, nil, :CallDIV), nil,
  s(:begin,
    s(:send, nil, :include,
      s(:const,
        s(:const, nil, :Hyperstack), :Component)),
    s(:def, :render,
      s(:args),
      s(:send, nil, :DIV))))
```

which yields
```ruby
class CallDIV
  include(Hyperstack::Component)
  def render
    DIV
  end
end
```

**Comment by catmando** [comment]
This patch fixes my case anyway
```ruby
module Unparser
  class Emitter
    # Emitter for send
    class Send < self
      def local_variable_clash?
        selector =~ /^[A-Z]/ || local_variable_scope.local_variable_defined_for_node?(node, selector)
      end
    end
  end
end
```
would you accept a cleanedup pull request (probaby rename `local_variable_clash?` to `const_or_local_variable_clash?`) etc.

**Comment by mbj** [comment]
@catmando I think your problem is in the same realm but not the exact same instance.

The bug @dkubb is reporting is one where a local variable clashes, and the bug you report is where unparser should use explicit method call syntax, to disambiguate from a constant reference.

The key difference here is that the local variable name clash needs to be detected against a traced local variable scope, where your case is detectable while only inspecting the current AST node (and not all its parents, as required to trace the lvar scope effective).

This is all fixable, your proposal is on the right track. Feel free to PR, try to stick to the style you see in the reminder of the code base.
